Av wrapper and perl update
Updated AV wrappers provided by Shawn Iverson and removed the old
“require” perl declaration from mailscanner.bin

diff --git a/mailscanner/lib/bitdefender-wrapper b/mailscanner/lib/bitdefender-wrapper
--- a/mailscanner/lib/bitdefender-wrapper
+++ b/mailscanner/lib/bitdefender-wrapper
@@ -34,6 +34,7 @@ prog=bdc
 extras=''
 
 #LogFile=/tmp/log.bdc.$$
+LogFile=$(mktemp) || { echo "$0: Cannot create temporary file" >&2; exit 1; }
 
 if [ -x ${PackageDir}/bdscan ]; then
   # Version 7.5 is installed
@@ -54,12 +55,13 @@ else
 fi
 
 if [ "x$1" = "x-IsItInstalled" ]; then
+  rm -f $LogFile
   [ -x ${PackageDir}/$prog ] && exit 0
   exit 1
 fi
 
 umask 077
-LogFile=$(mktemp) || { echo "$0: Cannot create temporary file" >&2; exit 1; }
+rm -f $LogFile
 ${PackageDir}/$prog --log=$LogFile $extras "$@" >/dev/null 2>&1
 cat $LogFile
 rm -f $LogFile
diff --git a/mailscanner/lib/clamav-wrapper b/mailscanner/lib/clamav-wrapper
--- a/mailscanner/lib/clamav-wrapper
+++ b/mailscanner/lib/clamav-wrapper
@@ -52,6 +52,7 @@
 # You may want to check this script for bash-isms
 
 #TempDir="/tmp/clamav.$$"
+TempDir=$(mktemp) || { echo "$0: Cannot make name for temporary dir" >&2; exit 1; }
 ClamUser="clamav"
 ClamGroup="clamav"
 
@@ -131,6 +132,7 @@ if [ ! -x $ClamScan ]; then
 fi
 
 if [ "x$1" = "x-IsItInstalled" ]; then
+  rm -f ${TempDir}
   [ -x $ClamScan ] && exit 0
   exit 1
 fi
@@ -139,10 +141,14 @@ fi
 PATH=$PATH:/usr/ucb
 export PATH
 
+# Check if the tmpdir exists, if so delete so we start with a clean slate
+if [ -x "${TempDir}" ]; then
+	rm -rf ${TempDir} >/dev/null 2>&1
+fi
 
 # Make the Temp dir
 umask 0077
-TempDir=$(mktemp -d) || { echo "$0: Cannot create temporary dir" >&2; exit 1; }
+mkdir "${TempDir}" >/dev/null 2>&1
 
 # In case we get interupted....
 trap "rm -rf ${TempDir}" EXIT
diff --git a/mailscanner/lib/kaspersky-wrapper b/mailscanner/lib/kaspersky-wrapper
--- a/mailscanner/lib/kaspersky-wrapper
+++ b/mailscanner/lib/kaspersky-wrapper
@@ -42,13 +42,15 @@ shift
 Scanner=kav4fs/bin/kav4fs-kavscanner
 if [ -x ${PackageDir}/$Scanner ]; then
   #Report=/tmp/kavoutput.tmp.$$
+  Report=$(mktemp) || { echo "$0: Cannot create temporary file" >&2; exit 1; }
   ScanOptions="-xp -i0" # Don't report progress, don't attempt to clean
   if [ "x$1" = "x-IsItInstalled" ]; then
+    rm -f $Report
     exit 0
   fi
 
   Args=`echo "$@" | sed -e 's/ -I/ -i/g; s/^-I/-i/g; s/-- / /g;'`
-  Report=$(mktemp) || { echo "$0: Cannot create temporary file" >&2; exit 1; }
+  rm -f $Report
   # 29/09/05 JKF Removed -j3 on advice from Kaspersky users
   ${PackageDir}/$Scanner $ScanOptions -o$Report -q "$@"
   cat $Report
@@ -60,13 +62,15 @@ fi
 Scanner=kav4unix/bin/kavscanner
 if [ -x ${PackageDir}/$Scanner ]; then
   #Report=/tmp/kavoutput.tmp.$$
+  Report=$(mktemp) || { echo "$0: Cannot create temporary file" >&2; exit 1; }
   ScanOptions="-xp -i0" # Don't report progress, don't attempt to clean
   if [ "x$1" = "x-IsItInstalled" ]; then
+    rm -f $Report
     exit 0
   fi
 
   Args=`echo "$@" | sed -e 's/ -I/ -i/g; s/^-I/-i/g; s/-- / /g;'`
-  Report=$(mktemp) || { echo "$0: Cannot create temporary file" >&2; exit 1; }
+  rm -f $Report
   # 29/09/05 JKF Removed -j3 on advice from Kaspersky users
   ${PackageDir}/$Scanner $ScanOptions -o$Report -q "$@"
   cat $Report
@@ -78,13 +82,15 @@ fi
 Scanner=bin/kavscanner
 if [ -x ${PackageDir}/$Scanner ]; then
   #Report=/tmp/kavoutput.tmp.$$
+  Report=$(mktemp) || { echo "$0: Cannot create temporary file" >&2; exit 1; }
   ScanOptions="-xp -i0" # Don't report progress, don't attempt to clean
   if [ "x$1" = "x-IsItInstalled" ]; then
+    rm -f $Report
     exit 0
   fi
 
   Args=`echo "$@" | sed -e 's/ -I/ -i/g; s/^-I/-i/g; s/-- / /g;'`
-  Report=$(mktemp) || { echo "$0: Cannot create temporary file" >&2; exit 1; }
+  rm -f $Report
   # 29/09/05 JKF Removed -j3 on advice from Kaspersky users
   ${PackageDir}/$Scanner $ScanOptions -o$Report -q "$@"
   cat $Report
